r"""Generate Siemens DVS file from Caruyer samples.

Convert unitary schema generated by http://www.emmanuelcaruyer.com/q-space-sampling.php
into a Siemens-readable format. Support variable number of
b-value=0 volumes, their interspersion in the sequeqnce, and
multiple b-values.

Examples
--------
python qspaceweight.py \
    --unitary-schema samples.txt \
    --num-b0 5 \
    --intersperse \
    --bvalues 1000 2000 3000

python qspaceweight.py \
    -u ~/Desktop/samples.txt \
    -n 5 \
    -i \
    -r \
    -b 1000 2000 3000

"""

import os
import sys
import pandas as pd
import numpy as np
import textwrap
import random
from argparse import ArgumentParser, RawTextHelpFormatter

type PT = str | os.PathLike


def get_args():
    """Get and parse arguments."""
    parser = ArgumentParser(
        description=__doc__, formatter_class=RawTextHelpFormatter
    )
    parser.add_argument(
        "-i",
        "--intersperse",
        action="store_true",
        help="Intersperse B0 volumes.",
    )
    parser.add_argument(
        "-r",
        "--randomize",
        action="store_true",
        help="Randomize direction order.",
    )

    required_args = parser.add_argument_group("Required Arguments")
    required_args.add_argument(
        "-u",
        "--unitary-schema",
        type=str,
        help="Sample.txt generated from http://www.emmanuelcaruyer.com/q-space-sampling.php",
        required=True,
    )
    required_args.add_argument(
        "-n",
        "--num-b0",
        type=int,
        help="Number of b-value=0 volumes.",
        required=True,
    )
    required_args.add_argument(
        "-b",
        "--bvalues",
        nargs="+",
        type=int,
        help="B-Values separated by spaces, number must match "
        + "the shells in [unitary_schema].",
        required=True,
    )

    if len(sys.argv) <= 1:
        parser.print_help(sys.stderr)
        sys.exit(0)

    return parser


def distribute_b0(directions: list, num_b0: int) -> list:
    """Distribute b-value=0 volumes throughout scan.

    First volume is b-value=0.

    Parameters
    ----------
    directions : list
        Strings of vectors containing shell value and XYZ directions.
    num_b0 : int
        Number of b-value=0 volumes.

    Returns
    -------
    list : direction list with intersperse b-value=0 volumes.

    """
    # Manage one b-zero
    b_zero = "( 0.000, 0.000, 0.000 )"
    if num_b0 == 1:
        return [b_zero] + directions

    # Determine block size
    num_dir = len(directions)
    block_size = num_dir // (num_b0 - 1)  # Account for starting b0

    # Start with b-value=0 volume, distribute b-zeroes
    new_dir = [b_zero]
    cnt_add_bval = 1
    for idx, vec in enumerate(directions):
        new_dir.append(vec)
        if ((idx + 1) % block_size) == 0:
            cnt_add_bval += 1
            new_dir.append(b_zero)

    # Catch-all by adding enough b_zero on end
    while cnt_add_bval < num_b0:
        new_dir.append(b_zero)
        cnt_add_bval += 1

    if cnt_add_bval != num_b0:
        raise ValueError(
            "Mismatch between requested and distributed b0 volumes."
        )
    return new_dir


def read_unitary(unitary_schema: PT) -> tuple:
    """Return unitary schema as np.ndarray and dict of shell counts."""
    # Read unitary as dataframe, conver to numpy
    df_sample = pd.read_table(
        unitary_schema,
        sep="\t",
        comment="#",
        header=None,
        names=["shell", "x", "y", "z"],
    )
    df_sample = df_sample.round({"x": 6, "y": 6, "z": 6})

    # Account for 0-vs-1 indexing
    shell_list = list(df_sample["shell"].unique())
    if 0 in shell_list:
        df_sample["shell"] = df_sample["shell"] + 1
    schema = df_sample.to_numpy()

    # Determine shell counts as sorted dict
    shell_counts = df_sample["shell"].value_counts().to_dict()
    shell_counts = {
        k: v for k, v in sorted(shell_counts.items(), key=lambda item: item[1])
    }

    return (schema, shell_counts)


def organize_schema(bvalues: list, schema: np.ndarray, rand: bool) -> list:
    """Organize schema np.ndarray into list of directions."""
    directions = []
    maxb = max(bvalues)
    for _, bvalue_vecs in enumerate(schema):

        # Use bvalue in weighting
        bvalue = bvalues[int(bvalue_vecs[0] - 1)]
        weight = np.sqrt(float(bvalue) / float(maxb))

        # Weight x, y, z directions
        xyz = bvalue_vecs[1:4]
        vec = xyz * weight
        vec = vec.round(6)
        directions.append(f"( {vec[0]}, {vec[1]}, {vec[2]} )")

    if rand:
        random.shuffle(directions)
    return directions


def _write_file(file_path: PT, file_info: str):
    """Write file_info to file_path."""
    file_info = textwrap.dedent(file_info)
    print(f"Writing file: {file_path}")
    with open(file_path, "w") as fd:
        fd.write(file_info)


def _switch_bval(bvalues: list) -> str:
    """Convert number of bvalues to word."""
    word_dict = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five"}
    return word_dict[len(bvalues)]


def write_siemens(
    directions: list,
    num_b0: int,
    bval_counts: dict,
    intersperse: bool,
    out_dir: PT,
):
    """Write siemens.dvs file from directions."""
    # Extract shell values and counts for writing dvs file
    b_word = _switch_bval(bval_counts)
    bval_ratio = ":".join(bval_counts.keys())
    bval_list = [f"b ={x}x{y}" for x, y in bval_counts.items()]
    num_dir = sum(bval_counts.values()) + num_b0
    num_shell = len(bval_counts.keys())
    int_bval_ratio = ":".join(
        [str(x + 1) for x, _ in enumerate(bval_counts.keys())]
    )

    # Write header
    siemens_info = textwrap.dedent(
        f"""\
        ### Gradient direction table optimized for NODDI + DTI combination.
        ###
        ### Diffusion directions are obtained using the online Q space
        ### sampling script by Emmanuel Caruyer
        ### http://www.emmanuelcaruyer.com/q-space-sampling.php
        ###
        ### Uniformly distributed directions in {num_shell} shells
        ### (bvalue ratio = {bval_ratio})
        ### {', '.join(bval_list)}, b =0x{num_b0}

        ## Reference:
        ## Caruyer, Emmanuel, Christophe Lenglet, Guillermo Sapiro, and
        ## Rachid Deriche. "Design of multishell sampling schemes with
        ## uniform coverage in diffusion MRI." Magnetic Resonance in Medicine
        ## 69, no. 6 (2013): 1534-1540.


        ## {b_word} interleaved shells. Interleaved bval ratio {int_bval_ratio}
        [directions={len(directions) + num_b0}]
        CoordinateSystem = xyz
        Normalisation = none
        """
    )
    siemens_file = os.path.join(
        out_dir, f"DiffusionVectors_{num_dir}dir_{num_shell}shells.dvs"
    )

    # Account for interspersal request
    if intersperse:
        directions = distribute_b0(directions, num_b0)
        for n, vec in enumerate(directions):
            siemens_info += f"Vector[{n}] = {vec}\n"
        _write_file(siemens_file, siemens_info)
        return

    # Non-intersperse b0 files are first.
    n = 0
    for _ in range(num_b0):
        siemens_info += f"Vector[{n}] = ( 0.000, 0.000, 0.000 )\n"
        n += 1
    for vec in directions:
        siemens_info += f"Vector[{n}] = {vec}\n"
        n += 1
    _write_file(siemens_file, siemens_info)


def main():
    """Convert unitary schema to siemens file."""
    # Capture args
    args = get_args().parse_args()
    unitary_schema = args.unitary_schema
    intersperse = args.intersperse
    bvalues = np.array(args.bvalues)
    num_b0 = args.num_b0
    rand = args.randomize

    # Read unitary
    out_dir = os.path.dirname(unitary_schema)
    schema, shell_counts = read_unitary(unitary_schema)

    # Switch shell_count keys to bvalues
    bval_counts = {}
    for num, bval in enumerate(bvalues):
        bval_counts[str(int(bval))] = shell_counts[num + 1]

    # Check number of shells in input schema:
    input_nshells = int(max([item[0] for item in schema]))
    given_bvalues = bvalues.size
    if input_nshells != given_bvalues:
        raise ValueError(
            "Given B-values number and provided Sample.txt "
            + "shells number doesn't match."
        )

    # Organize schema, write siemens file
    directions = organize_schema(bvalues, schema, rand)
    write_siemens(directions, num_b0, bval_counts, intersperse, out_dir)


if __name__ == "__main__":
    main()
